name: Build PR
on:
  pull_request_target:
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - run: git log
      - run: git diff origin/main HEAD

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Get branch
        id: getbranch
        run: |
          echo "##[set-output name=branch;]${GITHUB_HEAD_REF#refs/heads/}"
          echo "##[set-output name=safebranch;]$(echo -n "${GITHUB_HEAD_REF#refs/heads/}" | tr -c '[:alnum:]-' '-' | tr A-Z a-z)"

      - name: Determine next version (PR)
        uses: paulhatch/semantic-version@v5.4.0
        id: semverpr
        with:
          branch: ${{ steps.getbranch.outputs.branch }}
          tag_prefix: ${{ steps.getbranch.outputs.safebranch }}-v
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"
          debug: true
          
      # Since we are running a powershell script we have to specify the "shell" parameter. The default is "bash".
      - name: Run publish.ps1
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "GitHub Actions"
          build-scripts/publish.ps1 -VersionNumber "${{ steps.semverpr.outputs.version }}-${{ steps.getbranch.outputs.safebranch }}" -Tag "canary"
        shell: pwsh
        env:
          NPM_TOKEN: ${{ secrets.FORGE_NPM_TOKEN }}
